### ISSUE TITLE
Docker file on Docker Hub uses dev version?

### ISSUE THREAD

**Issue by hlapp** [rocker-org/ropensci#3]
It seems that the [Dockerfile used by Docker Hub for this image](https://hub.docker.com/r/rocker/ropensci/~/dockerfile/) is the one in the `dev/` folder here. Is that intentional? It would seem to make the Docker Hub image build recursive (due to the `FROM` line), but maybe I'm just not fully understanding.

**Comment by cboettig** [comment]
Docker hub builds both the one in the root dir (which depends on hadleyverse and becomes the docker image `rocker/ropensci:latest`, where the tag `latest` is implicit if left off), and also the one in the `dev` directory, which it tags as `rocker/ropensci:dev`.  As you see, the one in the `dev` directory depends on `rocker/ropensci`, but there is nothing strictly circular about this: tags point to separate Dockerfiles and any relation to other files with the same base name is purely convention, not technical.  

Does that make sense?  It might have been cleaner & more conventional just to repeat the code from Dockerfile for `rocker/ropensci` in the `dev` copy, but that opens things up to risk diverging.  

The only downside of this current setup is that the hub needs to be triggered twice before the `dev` copy is updated, which really isn't ideal.  Not sure what the best arrangement would be but open to suggestions.

**Comment by hlapp** [comment]
I guess the really confusing thing is that the Dockerfile tab shows only one Dockerfile, and it's apparently the one used for the `dev` tag, not the default (`latest`) tag.

And perhaps the relationship would be clearer if explicitly specifying the `:latest` tag in the `dev` Dockerfile?

The other part I found confusing is the purpose of the `dev/Dockerfile`. According to the README it installs packages from Github, but then it uses the `install2.r` and not the `installGithub.r` script, which seems self-contradictory. But I may just be missing something that's obvious to those who actually understand the modern way of doing things with R.

**Comment by cboettig** [comment]
@hlapp yeah, the Docker Hub is still a bit crude in that respect, in that the Dockerfile tab on the hub seems to unaware of the different tags for the repos.  Official repositories that follow this same tag structure aren't actually built directly from the hub anyway but are just pushed as binaries, and just link their Dockerfiles from the READMEs; e.g. see https://hub.docker.com/_/mysql/

The dev Dockerfile is installing GitHub dev copies because it is using our repo, `packages.ropensci.org`, in preference to the CRAN repo, to install those packages.  (However, it is only installing those packages listed manually.  In contrast, the ropensci:latest image is installing the current list of CRAN packages as listed by our `ropkgs` API, which is much more up to date and comprehensive.  

Though perhaps the existence of a `dev` image doesn't make sense given that we have a CRAN-style release strategy rather than a BioConductor one: (All CRAN-released packages are tested against each-other and guaranteed to be compatible, but we do not currently enforce the requirement that, say, github version of RNeXML is always compatible with github version taxize, say).

**Comment by hlapp** [comment]
Thanks for elucidating that, @cboettig! Who would have thought that `packages.ropensci.org` is really just GitHub versions 😄 (And curiously, I'm sure there is some reason that that's better than just using `installGithub.r`?)

**Comment by cboettig** [comment]
Dirk has some very nice material on that over at https://github.com/eddelbuettel/drat

**Comment by hlapp** [comment]
Thanks, alright. I guess case closed then.

**Comment by eddelbuettel** [comment]
Thanks for the drat pointer.  Documentation is also available via [my page here](http://dirk.eddelbuettel.com/code/drat.html), the drat gh-pages, and the package (which you linked to).
